
figure('Name', "Pressure Peak Detection");
axis(1) = subplot(2,2,1); 
hold on;
x = 1:length(Pressure); ix = PressureLag+1:length(Pressure);
area(x(ix),PressureAvg(ix)+PressureThreshold*PressureDev(ix),'FaceColor',[0.9 0.9 0.9],'EdgeColor','none');
area(x(ix),PressureAvg(ix)-PressureThreshold*PressureDev(ix),'FaceColor',[1 1 1],'EdgeColor','none');
plot(x(ix),PressureAvg(ix),'LineWidth',1,'Color','cyan','LineWidth',1.5);
plot(x(ix),PressureAvg(ix)+PressureThreshold*PressureDev(ix),'LineWidth',1,'Color','green','LineWidth',1.5);
plot(x(ix),PressureAvg(ix)-PressureThreshold*PressureDev(ix),'LineWidth',1,'Color','green','LineWidth',1.5);
plot(1:length(Pressure),Pressure,'b');
xlabel('Count');
ylabel('Pressure');
axis(3) = subplot(2,2,3);
hold on;
stairs(PressureSignals*5,'r','LineWidth',1.5); 
stairs(_PressureSignals*5,'y','LineWidth',1.5); 
##legend("PressureSignals", "_PressureSignals");
xlabel('Count');
ylabel('Pressure');
axis(4) = subplot(2,2,[2,4]); 
hold on;
x = 1:length(Pressure); ix = PressureLag+1:length(Pressure);
##area(x(ix),PressureAvg(ix)+PressureThreshold*PressureDev(ix),'FaceColor',[0.9 0.9 0.9],'EdgeColor','none');
##area(x(ix),PressureAvg(ix)-PressureThreshold*PressureDev(ix),'FaceColor',[1 1 1],'EdgeColor','none');
##plot(x(ix),PressureAvg(ix),'LineWidth',1,'Color','cyan','LineWidth',1.5);
##plot(x(ix),PressureAvg(ix)+PressureThreshold*PressureDev(ix),'LineWidth',1,'Color','green','LineWidth',1.5);
##plot(x(ix),PressureAvg(ix)-PressureThreshold*PressureDev(ix),'LineWidth',1,'Color','green','LineWidth',1.5);
plot(1:length(Pressure),Pressure,'b');
stairs(_PressureSignals*5,'y','LineWidth',1.5);
stairs(PressureSignals*5,'r','LineWidth',1.5); 
xlabel('Count');
ylabel('Pressure');

figure('Name', "Pressure Peak Detection");
##subplot(2,1,1); 
hold on;
x = 1:length(Pressure); ix = PressureLag+1:length(Pressure);
area(x(ix),PressureAvg(ix)+PressureThreshold*PressureDev(ix),'FaceColor',[0.9 0.9 0.9],'EdgeColor','none');
area(x(ix),PressureAvg(ix)-PressureThreshold*PressureDev(ix),'FaceColor',[1 1 1],'EdgeColor','none');
plot(x(ix),PressureAvg(ix),'LineWidth',1,'Color','cyan','LineWidth',1.5);
plot(x(ix),PressureAvg(ix)+PressureThreshold*PressureDev(ix),'LineWidth',1,'Color','green','LineWidth',1.5);
plot(x(ix),PressureAvg(ix)-PressureThreshold*PressureDev(ix),'LineWidth',1,'Color','green','LineWidth',1.5);
plot(1:length(Pressure),Pressure,'b');
##subplot(2,1,2);
stairs(_PressureSignals*5,'y','LineWidth',1.5); 
stairs(PressureSignals*5,'r','LineWidth',1.5); 
##ylim([-1.5 1.5]);